security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'
    
    providers:
        users_storage:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_storage
            custom_authenticator: App\Security\AppLoginAuthenticator
            logout:
                path: user_logout
                target: main_index
            remember_me:
                secret: '%kernel.secret%'
                name: KEEPLOGIN
                lifetime: 604800
                remember_me_parameter: '_keep_login'

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
