parameters:
    payment:
        publicKey: '%env(resolve:STRIPE_PUBLIC_KEY)%'
        privateKey: '%env(resolve:STRIPE_PRIVATE_KEY)%'
        currency: EUR
    media:
        path: '%kernel.project_dir%/public/data'

services:
    _defaults:
        autowire: true      
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

